# Generated by Django 5.0.3 on 2024-03-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code1', models.CharField(max_length=100)),
                ('ticket_name', models.CharField(max_length=100)),
                ('booking_code', models.CharField(max_length=100)),
                ('ticket_price', models.CharField(max_length=100)),
                ('ticket_date', models.CharField(max_length=100)),
                ('expiration_date', models.CharField(max_length=100)),
                ('code2', models.CharField(max_length=100)),
            ],
        ),
    ]
