# Generated by Django 5.0.3 on 2024-04-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0002_alter_ticketmodel_ticket_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='code3',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
