# Generated by Django 5.0.3 on 2024-04-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0003_ticketmodel_code3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticket_date',
            field=models.CharField(max_length=10),
        ),
    ]
