# Generated by Django 5.0.4 on 2024-04-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0005_alter_ticketmodel_ticket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticket_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticket_price',
            field=models.CharField(max_length=100),
        ),
    ]
